"""Build the five-year Excel model (deliverable 2) FROM the pipeline dataset.

Design contract:
  - Every editable assumption is a YELLOW named cell on '1 Assumptions'.
    The Model, Sensitivity and Compare tabs are pure formulas over those
    names - change any yellow cell and the whole workbook recalculates
    (built for the live session).
  - Pipeline-supplied inputs are GREY cells, each with its source shown.
  - '5 Sources' is written from the pipeline's provenance records: for every
    input - where it came from and whether it is pack / derived / estimated.
"""
import json
from datetime import datetime, timezone

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.workbook.defined_name import DefinedName

from .util import ROOT
from .paths import ws_dir, latest_run, DEFAULT_WS

INK = "1D2939"; SOFT = "667085"; LINE = "E6E1DA"
ACC = "374B60"; ACCSOFT = "E6EEF3"; YELL = "F6EAD9"; GREY = "EFECE7"
FAILSOFT = "F8E3DC"; OK = "374B60"

F_TITLE = Font(name="Calibri", size=16, bold=True, color=INK)
F_H = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
F_SEC = Font(name="Calibri", size=11, bold=True, color="C12D00")
F_B = Font(name="Calibri", size=11, color=INK)
F_BOLD = Font(name="Calibri", size=11, bold=True, color=INK)
F_SM = Font(name="Calibri", size=9, color=SOFT, italic=True)
FILL_H = PatternFill("solid", fgColor=INK)
FILL_IN = PatternFill("solid", fgColor=YELL)
FILL_PIPE = PatternFill("solid", fgColor=GREY)
FILL_ACC = PatternFill("solid", fgColor=ACCSOFT)
FILL_BAD = PatternFill("solid", fgColor=FAILSOFT)
THIN = Side(style="thin", color=LINE)
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

EUR = '#,##0'
EURM = '#,##0,,"M"'
PCT = '0.0%'


def _name(wb, name, sheet, cell):
    ref = f"'{sheet}'!${cell[0]}${cell[1:]}" if cell[0].isalpha() and cell[1:].isdigit() else f"'{sheet}'!{cell}"
    dn = DefinedName(name, attr_text=ref)
    try:
        wb.defined_names.add(dn)
    except AttributeError:
        wb.defined_names[name] = dn


def _set(ws, cell, value, font=F_B, fill=None, fmt=None, border=True, align=None):
    c = ws[cell]
    c.value = value
    c.font = font
    if fill:
        c.fill = fill
    if fmt:
        c.number_format = fmt
    if border:
        c.border = BORDER
    if align:
        c.alignment = Alignment(horizontal=align)
    return c


def build(state=None) -> str:
    state = state or json.load(open(latest_run(ws_dir(DEFAULT_WS)) / "state.json"))
    ds = state["dataset"]
    res = state["conclusion"]["results"]
    ranking = state["conclusion"]["ranking"]
    rec = state["conclusion"]["recommendation"]
    nlp = {p: e["value"] for p, e in ds[rec].items()}
    comp = {p: e["value"] for p, e in ds["company"].items()}

    wb = Workbook()

    # ---------------- 0 Read Me ----------------
    ws = wb.active
    ws.title = "0 Read Me"
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["B"].width = 100
    _set(ws, "B2", "HelixColon — five-year market-entry model", F_TITLE, border=False)
    _set(ws, "B3", f"Selected market: {rec} · generated by the data pipeline · "
         f"{datetime.now(timezone.utc):%d %b %Y}", F_SM, border=False)
    rows = [
        ("How to use", F_SEC),
        ("Every YELLOW cell on '1 Assumptions' is editable. The Model, Sensitivity and Compare tabs are pure "
         "formulas over those cells — change an assumption and the whole workbook recalculates.", F_B),
        ("GREY cells are pipeline-extracted inputs; their origin is recorded next to them and, in full, "
         "on '5 Sources'. Corrections belong in the pipeline's overrides.yaml, not typed over outputs.", F_B),
        ("", F_B),
        ("Structure", F_SEC),
        ("1 Assumptions — the editable layer (commercial + cost assumptions) and the pipeline market inputs.", F_B),
        ("2 Model — volume funnel → unit economics → P&L → cash runway for the selected market.", F_B),
        ("3 Sensitivity — a live scenario engine: penetration ramp ×50–125% against reimbursement delay "
         "12/18/24 months; break-even, cash trough and end-cash grids.", F_B),
        ("4 Compare — the four candidate markets through the same engine (pipeline-computed).", F_B),
        ("5 Sources — every input: value, origin file, extraction method, and pack / derived / estimated.", F_B),
        ("", F_B),
        ("Conventions", F_SEC),
        ("All figures EUR. Years are calendar years from entry (Y1 = entry year). Annual granularity; "
         "reimbursement delays round up to full years (conservative).", F_B),
    ]
    r = 5
    for text, font in rows:
        _set(ws, f"B{r}", text, font, border=False)
        ws[f"B{r}"].alignment = Alignment(wrap_text=True, vertical="top")
        r += 1
    ws["A1"].value = ""

    # ---------------- 1 Assumptions ----------------
    ws = wb.create_sheet("1 Assumptions")
    ws.sheet_view.showGridLines = False
    for col, w in zip("ABCDE", (2, 44, 16, 10, 58)):
        ws.column_dimensions[col].width = w
    _set(ws, "B2", "Assumptions — the editable layer", F_TITLE, border=False)
    _set(ws, "B3", "Yellow = change me (live session). Grey = pipeline input with source.", F_SM, border=False)

    def header(row, label):
        _set(ws, f"B{row}", label, F_H, FILL_H)
        _set(ws, f"C{row}", "Value", F_H, FILL_H)
        _set(ws, f"D{row}", "Unit", F_H, FILL_H)
        _set(ws, f"E{row}", "Basis", F_H, FILL_H)

    r = 5
    header(r, "A · Commercial assumptions (EDITABLE)")
    assumptions = [
        ("Penetration ramp — reimbursed year 1", 0.07, "% addr", "ramp1",
         "Anchored to pack benchmark: comparable assay ≈20% of eligible volume within 3 years of reimbursement"),
        ("Penetration ramp — year 2", 0.13, "% addr", "ramp2", "interpolation toward the 20% benchmark"),
        ("Penetration ramp — year 3", 0.20, "% addr", "ramp3", "the benchmark itself"),
        ("Penetration ramp — year 4", 0.22, "% addr", "ramp4", "modest continued growth past benchmark"),
        ("Penetration ramp — year 5", 0.24, "% addr", "ramp5", "modest continued growth past benchmark"),
        ("Months to reimbursed revenue", nlp["time_to_reimbursement_months"], "months", "delay_m",
         f"pack: {rec} national report (~12 months, single national procurement route)"),
        ("Price per test", nlp["price_per_test"], "EUR", "price", f"pack: {rec} national report tariff guidance"),
        ("COGS per test — year 1", comp["cogs_year1"], "EUR", "cogs1", "pack: company briefing"),
        ("COGS per test — year 5", comp["cogs_year5"], "EUR", "cogs5", "pack: company briefing (linear in between)"),
    ]
    r += 1
    for label, val, unit, nm, basis in assumptions:
        _set(ws, f"B{r}", label, F_B)
        c = _set(ws, f"C{r}", val, F_BOLD, FILL_IN, PCT if unit == "% addr" else EUR)
        _set(ws, f"D{r}", unit, F_SM)
        _set(ws, f"E{r}", basis, F_SM)
        _name(wb, nm, "1 Assumptions", f"C{r}")
        r += 1
    ramp_first, ramp_last = 6, 10
    _name(wb, "ramp", "1 Assumptions", f"$C${ramp_first}:$C${ramp_last}")

    r += 1
    header(r, "B · Cost structure (EDITABLE)")
    r += 1
    for label, val, nm, basis in [
        ("Corporate operating cost / year", comp["corporate_cost_per_year"], "corp", "pack: company briefing (HQ, R&D, G&A — incurred regardless of market)"),
        (f"In-market commercial cost / year — {rec}", nlp["inmarket_cost_per_year"], "inmkt", "pack: landscape table (internal estimate)"),
        (f"One-time entry cost — {rec}", nlp["entry_cost"], "entry", "pack: landscape table (internal estimate)"),
        ("Cash on hand at entry", comp["cash_runway"], "cash0", "pack: company briefing"),
    ]:
        _set(ws, f"B{r}", label, F_B)
        _set(ws, f"C{r}", val, F_BOLD, FILL_IN, EUR)
        _set(ws, f"D{r}", "EUR", F_SM)
        _set(ws, f"E{r}", basis, F_SM)
        _name(wb, nm, "1 Assumptions", f"C{r}")
        r += 1

    r += 1
    header(r, f"C · Market inputs — {rec} (pipeline-extracted)")
    r += 1
    for label, val, nm, fmt, basis in [
        ("Eligible population 50–74", nlp["eligible_population"], "elig", EUR, "pack: national screening report"),
        ("Programme participation", nlp["participation"], "part", PCT, "pack: national screening report"),
        ("FIT positivity rate", nlp["fit_positivity"], "pos", PCT, "pack: national screening report"),
        ("Colonoscopy reimbursement tariff", nlp["colonoscopy_tariff"], "tariff", EUR, "pack: national screening report"),
        ("Safe deferral rate (clinical study)", comp["deferral_rate"], "defer", PCT, "pack: company briefing — 1,200-patient prospective study"),
    ]:
        _set(ws, f"B{r}", label, F_B)
        _set(ws, f"C{r}", val, F_BOLD, FILL_PIPE, fmt)
        _set(ws, f"D{r}", "", F_SM)
        _set(ws, f"E{r}", basis, F_SM)
        _name(wb, nm, "1 Assumptions", f"C{r}")
        r += 1

    # ---------------- 2 Model ----------------
    ws = wb.create_sheet("2 Model")
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 2
    ws.column_dimensions["B"].width = 34
    for i in range(5):
        ws.column_dimensions[get_column_letter(3 + i)].width = 14
    ws.column_dimensions["H"].width = 46
    _set(ws, "B2", f"{rec} — five-year model", F_TITLE, border=False)
    _set(ws, "B3", "Formulas only — driven entirely by '1 Assumptions'.", F_SM, border=False)

    _set(ws, "B5", "Addressable FIT-positive / year", F_BOLD, FILL_ACC, EUR)
    _set(ws, "C5", "=elig*part/2*pos", F_BOLD, FILL_ACC, EUR)
    _set(ws, "H5", "eligible × participation ÷ 2 (biennial) × positivity", F_SM, border=False)
    _name(wb, "addr", "2 Model", "C5")
    _set(ws, "B6", "Revenue offset (years, delay rounded up)", F_B)
    _set(ws, "C6", "=CEILING(delay_m/12,1)", F_B, fmt="0")
    _name(wb, "offs", "2 Model", "C6")

    hdr_row = 8
    _set(ws, f"B{hdr_row}", "P&L and cash", F_H, FILL_H)
    for i in range(5):
        _set(ws, f"{get_column_letter(3+i)}{hdr_row}", f"Y{i+1}", F_H, FILL_H, align="center")
    _set(ws, f"H{hdr_row}", "Formula logic", F_H, FILL_H)

    def yrcols():
        return [get_column_letter(3 + i) for i in range(5)]

    rows_spec = [
        ("Ramp (share of addressable)", PCT,
         lambda i, c: f"=IF({i+1}>offs,INDEX(ramp,MIN({i+1}-offs,5)),0)",
         "0 until reimbursement; then the assumption ramp"),
        ("Tests processed", EUR, lambda i, c: f"={c}9*addr", "ramp × addressable"),
        ("COGS per test", '0.00', lambda i, c: f"=cogs1+(cogs5-cogs1)*{i}/4", "linear 58 → 44 (pack)"),
        ("Revenue", EUR, lambda i, c: f"={c}10*price", "tests × price"),
        ("Cost of goods", EUR, lambda i, c: f"=-{c}10*{c}11", "tests × COGS/test"),
        ("Gross margin", EUR, lambda i, c: f"={c}12+{c}13", ""),
        ("In-market commercial cost", EUR, lambda i, c: "=-inmkt", "landscape internal estimate"),
        ("Corporate operating cost", EUR, lambda i, c: "=-corp", "incurred regardless of market"),
        ("EBITDA (company level)", EUR, lambda i, c: f"={c}14+{c}15+{c}16", ""),
        ("EBITDA-positive flag", '0', lambda i, c: f"=IF({c}17>0,1,0)", "helper for break-even lookup"),
        ("Cash (year end)", EUR,
         lambda i, c: "=cash0-entry+C17" if i == 0 else f"={get_column_letter(2+i)}19+{c}17",
         "entry cost deducted in Y1"),
    ]
    for j, (label, fmt, fx, note) in enumerate(rows_spec):
        rr = 9 + j
        _set(ws, f"B{rr}", label, F_BOLD if label in ("Gross margin", "EBITDA (company level)", "Cash (year end)") else F_B)
        for i, c in enumerate(yrcols()):
            _set(ws, f"{c}{rr}", fx(i, c), F_B, fmt=fmt)
        _set(ws, f"H{rr}", note, F_SM, border=False)
    ws.row_dimensions[18].hidden = True  # helper row

    orow = 21
    _set(ws, f"B{orow}", "Outputs", F_H, FILL_H)
    _set(ws, f"C{orow}", "", F_H, FILL_H)
    _set(ws, f"D{orow}", "", F_H, FILL_H)
    outs = [
        ("Break-even year (EBITDA > 0)", '=IFERROR("Y"&MATCH(1,C18:G18,0),"beyond Y5")', '@'),
        ("Cash trough (minimum cash)", "=MIN(C19:G19)", EUR),
        ("End cash, Y5", "=G19", EUR),
        ("Runway check", '=IF(C23<0,"INSOLVENT — runway exhausted","survives on current assumptions")', '@'),
        ("System saving per 100 FIT+ triaged", "=defer*100*tariff-100*price", EUR),
    ]
    for j, (label, fx, fmt) in enumerate(outs):
        _set(ws, f"B{orow+1+j}", label, F_BOLD)
        _set(ws, f"C{orow+1+j}", fx, F_BOLD, FILL_ACC, fmt)
    _set(ws, f"H{orow+2}", "the number the board should watch", F_SM, border=False)
    _set(ws, f"H{orow+5}", "each avoided colonoscopy (45/100) saves the tariff; each test costs the price", F_SM, border=False)

    # ---------------- 3 Sensitivity ----------------
    ws = wb.create_sheet("3 Sensitivity")
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 2
    for col in "BCDEFGHIJKLMNOPQRS":
        ws.column_dimensions[col].width = 11.5
    ws.column_dimensions["B"].width = 15
    _set(ws, "B2", "Sensitivity — live scenario engine", F_TITLE, border=False)
    _set(ws, "B3", "Every cell is a formula over the same named assumptions; the grids recalc with the model.", F_SM, border=False)

    mults = [0.50, 0.75, 1.00, 1.25]
    delays = [12, 18, 24]
    eng_row = 6
    _set(ws, f"B{eng_row}", "Engine (12 scenarios)", F_H, FILL_H)
    hdrs = ["mult", "delay", "offs"] + [f"EBITDA Y{i+1}" for i in range(5)] + [f"Cash Y{i+1}" for i in range(5)] + ["BE year", "Min cash", "End cash"]
    for k, h in enumerate(hdrs):
        _set(ws, f"{get_column_letter(3+k)}{eng_row}", h, F_H, FILL_H)
    ri = eng_row + 1
    scen_rows = []
    for mu in mults:
        for de in delays:
            C_ = lambda k: f"{get_column_letter(3+k)}{ri}"
            _set(ws, f"B{ri}", f"×{mu:.2f} / {de}m", F_SM)
            _set(ws, C_(0), mu, F_B, fmt='0%')
            _set(ws, C_(1), de, F_B, fmt='0')
            _set(ws, C_(2), f"=CEILING({C_(1)}/12,1)", F_B, fmt='0')
            for y in range(1, 6):
                ebitda = (f"=IF({y}>{C_(2)},INDEX(ramp,MIN({y}-{C_(2)},5)),0)*{C_(0)}*addr"
                          f"*(price-(cogs1+(cogs5-cogs1)*{y-1}/4))-inmkt-corp")
                _set(ws, C_(2 + y), ebitda, F_B, fmt=EURM)
            for y in range(1, 6):
                prev = "cash0-entry" if y == 1 else C_(7 + y - 1)
                _set(ws, C_(7 + y), f"={prev}+{C_(2+y)}", F_B, fmt=EURM)
            be = (f'=IF({C_(3)}>0,1,IF({C_(4)}>0,2,IF({C_(5)}>0,3,'
                  f'IF({C_(6)}>0,4,IF({C_(7)}>0,5,"—")))))')
            _set(ws, C_(13), be, F_B, fmt='0')
            _set(ws, C_(14), f"=MIN({C_(8)}:{C_(12)})", F_B, fmt=EURM)
            _set(ws, C_(15), f"={C_(12)}", F_B, fmt=EURM)
            scen_rows.append(ri)
            ri += 1

    grid_top = ri + 2
    for gi, (title, col_idx, fmt) in enumerate([
            ("Cash trough (EUR M) — the survival grid", 14, EURM),
            ("Break-even year", 13, '0'),
            ("End cash Y5 (EUR M)", 15, EURM)]):
        base = grid_top + gi * (len(mults) + 4)
        _set(ws, f"B{base}", title, F_SEC, border=False)
        _set(ws, f"B{base+1}", "ramp ↓ / delay →", F_SM, FILL_H)
        for dj, de in enumerate(delays):
            _set(ws, f"{get_column_letter(3+dj)}{base+1}", f"{de} months", F_H, FILL_H)
        for mi, mu in enumerate(mults):
            _set(ws, f"B{base+2+mi}", f"ramp ×{mu:.0%}", F_B, FILL_PIPE)
            for dj, de in enumerate(delays):
                src_row = scen_rows[mi * len(delays) + dj]
                cell = f"{get_column_letter(3+dj)}{base+2+mi}"
                _set(ws, cell, f"={get_column_letter(3+col_idx)}{src_row}", F_B, fmt=fmt)
    _set(ws, f"B{grid_top-1}", "Presentation grids", F_H, FILL_H)

    # ---------------- 4 Compare ----------------
    ws = wb.create_sheet("4 Compare")
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 2
    ws.column_dimensions["B"].width = 30
    for i in range(4):
        ws.column_dimensions[get_column_letter(3 + i)].width = 16
    _set(ws, "B2", "The four candidate markets — same engine", F_TITLE, border=False)
    _set(ws, "B3", "Pipeline-computed (stage 7); the selected market is replicated live on '2 Model'.", F_SM, border=False)
    r = 5
    _set(ws, f"B{r}", "Metric", F_H, FILL_H)
    order = ranking
    for i, m in enumerate(order):
        _set(ws, f"{get_column_letter(3+i)}{r}", f"{i+1}. {m}", F_H, FILL_H, align="center")
    metrics = [
        ("Eligible population 50–74", lambda m: ds[m]["eligible_population"]["value"], EUR, None),
        ("Participation", lambda m: ds[m]["participation"]["value"], PCT, None),
        ("FIT positivity", lambda m: ds[m]["fit_positivity"]["value"], PCT, None),
        ("Addressable FIT+ / yr", lambda m: ds[m]["addressable_fit_positive"]["value"], EUR, None),
        ("Price per test", lambda m: ds[m]["price_per_test"]["value"], EUR, None),
        ("Months to reimbursement", lambda m: ds[m]["time_to_reimbursement_months"]["value"], '0', None),
        ("Entry cost", lambda m: ds[m]["entry_cost"]["value"], EUR, None),
        ("In-market cost / yr", lambda m: ds[m]["inmarket_cost_per_year"]["value"], EUR, None),
        ("Break-even year", lambda m: res[m]["break_even_year"] or "beyond Y5", '@', None),
        ("Cash trough", lambda m: res[m]["min_cash"], EUR, "risk"),
        ("End cash Y5", lambda m: res[m]["end_cash"], EUR, None),
        ("Verdict", lambda m: "SURVIVES" if not res[m]["insolvent"] else "INSOLVENT", '@', "verdict"),
    ]
    r += 1
    for label, get, fmt, kind in metrics:
        _set(ws, f"B{r}", label, F_B)
        for i, m in enumerate(order):
            v = get(m)
            cell = f"{get_column_letter(3+i)}{r}"
            fill = FILL_PIPE
            font = F_B
            if kind == "verdict" or (kind == "risk" and isinstance(v, (int, float)) and v < 0):
                fill = FILL_ACC if v in ("SURVIVES",) else FILL_BAD
                font = F_BOLD
            _set(ws, cell, v, font, fill, fmt)
        r += 1
    r += 1
    _set(ws, f"B{r}", "Why Germany is 2nd despite the largest volume: the 24-month pathway consumes the €4M runway "
         "before first reimbursed revenue (pre-reimbursement revenue 'immaterial' per its national report), and an "
         "incumbent holds 35–40% of the channel. Right market later — unaffordable first.", F_SM, border=False)
    ws[f"B{r}"].alignment = Alignment(wrap_text=True)
    ws.merge_cells(f"B{r}:F{r+2}")

    # ---------------- 5 Sources ----------------
    ws = wb.create_sheet("5 Sources")
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 2
    for col, w in zip("BCDEFG", (14, 30, 14, 12, 30, 44)):
        ws.column_dimensions[col].width = w
    _set(ws, "B2", "Sources — every input, its origin", F_TITLE, border=False)
    _set(ws, "B3", "pack = read from a pack document · derived = computed from pack values · "
         "estimated = modelling assumption (basis stated) · manual = overrides.yaml", F_SM, border=False)
    r = 5
    for k, h in enumerate(["Scope", "Parameter", "Value", "Class", "Source", "Detail"]):
        _set(ws, f"{get_column_letter(2+k)}{r}", h, F_H, FILL_H)
    r += 1
    class_map = {"DET": "pack", "INTERNAL": "derived", "MANUAL": "manual", "LLM": "pack (AI-extracted)"}
    for scope in ["company", "competitor", "funding"] + [m for m in ["Portugal", "Germany", "Netherlands", "Poland"] if m in ds]:
        for p, e in sorted(ds[scope].items()):
            _set(ws, f"B{r}", scope, F_SM)
            _set(ws, f"C{r}", p, F_B)
            _set(ws, f"D{r}", e["value"], F_B, fmt='General')
            cls = class_map.get(e["method"], e["method"])
            _set(ws, f"E{r}", cls, F_B, FILL_PIPE if cls == "pack" else (FILL_ACC if cls == "derived" else FILL_IN))
            _set(ws, f"F{r}", e["source"], F_SM)
            _set(ws, f"G{r}", str(e["pattern"])[:90], F_SM)
            r += 1
    for label, cls, src, detail in [
        ("penetration ramp Y1–Y5", "estimated", "1 Assumptions", "anchored to the pack's benchmark (~20% of eligible volume within 3 years of reimbursement); ±50% bracketed in Sensitivity"),
        ("reimbursement delay", "pack", f"{rec} national report", "12 months; stress-tested at 18/24 in Sensitivity"),
        ("annual model granularity", "estimated", "modelling choice", "delays round UP to whole years — conservative"),
        ("Germany pre-reimbursement revenue = 0", "pack", "Germany national report", "'planning assumptions should treat pre-reimbursement revenue as immaterial'"),
        ("OncoStream 300k tests/yr", "REJECTED", "competitor brief", "fails arithmetic vs primary sources (1.7× the whole German addressable market) — see pipeline check CHK-02"),
    ]:
        _set(ws, f"B{r}", "model", F_SM)
        _set(ws, f"C{r}", label, F_B)
        _set(ws, f"D{r}", "", F_B)
        _set(ws, f"E{r}", cls, F_B, FILL_BAD if cls == "REJECTED" else FILL_IN if cls == "estimated" else FILL_PIPE)
        _set(ws, f"F{r}", src, F_SM)
        _set(ws, f"G{r}", detail, F_SM)
        r += 1

    out = ROOT.parent / "deliverables" / "Helix_Optics_5Y_Model_NL.xlsx"
    out.parent.mkdir(exist_ok=True)
    wb.save(out)
    return str(out)


if __name__ == "__main__":
    print(build())
